repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

-   repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
        - id: yapf
          args: [
            '--style=.style.yapf',
            '--parallel',
            '--in-place',
            '--recursive',
            '--verbose',
          ]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=119',
          '--max-complexity=10',
          "--inline-quotes='",
          '--exclude=.venv, migrations',
          '--ignore=E722, D100, D101, D102, D103, D104, D105, D106, D400, I100, I201',
        ]
        additional_dependencies:
          - flake8-bugbear
          - flake8-import-order
          - flake8-docstrings
          - flake8-quotes
          - flake8-commas
          - flake8-builtins
