# Generated by Django 3.2.18 on 2023-05-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={
                'verbose_name': 'Movie Rating',
                'verbose_name_plural': 'Movie Ratings'
            },
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={
                'ordering': ['-value'],
                'verbose_name': 'Rating Star',
                'verbose_name_plural': 'Rating Stars'
            },
        ),
    ]
