from os import environ

RECAPTCHA_PUBLIC_KEY = environ['RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY = environ['RECAPTCHA_PRIVATE_KEY']
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5
